[package]
name = "virtual_cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.1.3"
rdev = "0.5.3"

[dependencies.windows]
version = "0.52"
features = ["Win32_UI_Input_KeyboardAndMouse"]
